databases:
  - name: sessions-db
    databaseName: sessions
    plan: free

services:
  - type: web
    name: fullstack-app
    runtime: node
    plan: free
    buildCommand: |
      cd backend && npm install
      echo "Checking directory structure..."
      ls -la
      cd ..
      ls -la
      echo "Frontend files:"
      ls -la frontend/
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: sessions-db
          property: connectionString
